name: Deploy Lambda Function SFTP To S3 Code

on:
  push:
    branches:
      - master  # Trigger deployment when you push to the master branch, we can add the main branch later

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Get list of changed files
      id: changes
      run: |
        git fetch --depth=2
        git diff --name-only HEAD^ HEAD > changed_files.txt

    - name: Display changed files
      run: cat changed_files.txt

    - name: Zip changed files only
      run: |
        mkdir lambda_function_code
        xargs -a changed_files.txt -I {} cp --parents {} lambda_function_code/
        zip -r lambda_function_code.zip lambda_function_code/ \
        -x "*.git*" "*.zip" "*.gitignore"
    
    - name: Install AWS CLI
      run: sudo apt-get install -y awscli      

    - name: Deploy code to Lambda
      run: |
        aws lambda update-function-code \
          --function-name py_sftp_s3_file_transfer \
          --zip-file fileb://lambda_function_code.zip
