name: Deploy Lambda Function SFTP To S3 Code

on:
  push:
    branches:
      - master  # Trigger deployment when you push to the master branch, we can add the main branch later

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Zip Lambda function code
      run: |
        zip -r lambda_function_code.zip . \
        -x '*.git*' '*.zip' # Exclude .git, .zip files

    - name: Deploy code to Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: py_sftp_s3_file_transfer
        zip-file: lambda_function_code.zip
